application: 
  host: ford.rewura.com

ingress: 
  api: 
    fullName: nginx-ingress-api-prod
  oauth2: 
    fullName: nginx-ingress-oauth2-prod
  frontend: 
    fullName: nginx-ingress-frontend-prod
  frontend_oauth: 
    fullName: nginx-ingress-frontend-oauth-prod

service:
  appointment: 
    serviceName: appointment-service
    port: 8305
    portType: ClusterIP
    image: gabendockerzone/appointment-service:f778bb2
    componentSelector: appointment-server
  frontend: 
    serviceName: frontend-service
    port: 8301
    portType: ClusterIP
    image: gabendockerzone/frontend:40c3c62
    componentSelector: web
  postgres: 
    serviceName: postgres-service
    port: 5432
    portType: NodePort
    image: postgres
    componentSelector: postgres
  authorization: 
    serviceName: authorization-service
    port: 8302
    portType: ClusterIP
    image: gabendockerzone/authorization-service:e41e2293
    componentSelector: server
  file: 
    serviceName: file-upload-service
    port: 8303
    portType: ClusterIP
    image: gabendockerzone/file-upload-service:20aad91
    componentSelector: server-inquiry
  inquiry: 
    serviceName: inquiry-service
    port: 8404
    portType: ClusterIP
    image: gabendockerzone/inquiry-service:8a588ba
    componentSelector: server-inquiry

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80