apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: appointment-server
  template:
    metadata:
      labels:
        component: appointment-server
    spec:
      containers:
        - name: appointment-service
          image: "{{ .Values.service.appointment.image }}"
          ports:
            - containerPort: 8305