apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: file-upload-service
  template:
    metadata:
      labels:
        component: file-upload-service
    spec:
      containers:
        - name: file-upload-service
          image: "{{ .Values.service.file.image }}"
          ports:
            - containerPort: {{ .Values.service.file.port }}