apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  type: ClusterIP
  selector:
    component: file-upload-service
  ports:
    - port: {{ .Values.service.file.port }}
      targetPort: {{ .Values.service.file.port }}
