apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-inquiry
  template:
    metadata:
      labels:
        component: server-inquiry
    spec:
      containers:
        - name: inquiry-service
          image: "{{ .Values.service.inquiry.image }}"
          ports:
            - containerPort: 8304
          env:
            - name: DATASOURCE_URL
              value: "jdbc:postgresql://postgres-postgresql.managed/postgres?currentSchema=ford_inquiry"
            - name: DATASOURCE_USER
              value: postgres
            - name: DATASOURCE_PASSWORD
              value: postgres
            - name: ZIPKIN_BASE_URL
              value: "http://zipkin-collector:9411"
            - name: TEST_MODE_ENABLED
              value: 'false'