apiVersion: v1
kind: Service
metadata:
  name: inquiry-service
spec:
  type: ClusterIP
  selector:
    component: server-inquiry
  ports:
    - port: {{ .Values.service.inquiry.port }}
      targetPort: {{ .Values.service.inquiry.port }}
